///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest4
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest4Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a57be1fa-833d-4bb4-9352-6e07ac5c49d1")]
    public partial class MyTest4Repository : RepoGenBaseFolder
    {
        static MyTest4Repository instance = new MyTest4Repository();
        MyTest4RepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder _entrendueruenlertuerkiyeninonlineal;
        MyTest4RepositoryFolders.TRENDYOLMANLimitedEditionAntrasitErAppFolder _trendyolmanlimitededitionantrasiter;
        MyTest4RepositoryFolders.RonarexHowToStartChromeAppGoogleAppFolder _ronarexhowtostartchromeappgoogle;
        MyTest4RepositoryFolders.TRENDYOLMANAntrasitErkekBasicRegulaAppFolder _trendyolmanantrasiterkekbasicregula;
        MyTest4RepositoryFolders.TuemUEruenlerTrendyolGoogleChromAppFolder _tuemueruenlertrendyolgooglechrom;
        MyTest4RepositoryFolders.TRENDYOLMANIndigoErkekOversizeFitGAppFolder _trendyolmanindigoerkekoversizefitg;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest4Repository element repository.
        /// </summary>
        [RepositoryFolder("a57be1fa-833d-4bb4-9352-6e07ac5c49d1")]
        public static MyTest4Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest4Repository() 
            : base("MyTest4Repository", "/", null, 0, false, "a57be1fa-833d-4bb4-9352-6e07ac5c49d1", ".\\RepositoryImages\\MyTest4Repositorya57be1fa.rximgres")
        {
            _entrendueruenlertuerkiyeninonlineal = new MyTest4RepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(this);
            _trendyolmanlimitededitionantrasiter = new MyTest4RepositoryFolders.TRENDYOLMANLimitedEditionAntrasitErAppFolder(this);
            _ronarexhowtostartchromeappgoogle = new MyTest4RepositoryFolders.RonarexHowToStartChromeAppGoogleAppFolder(this);
            _trendyolmanantrasiterkekbasicregula = new MyTest4RepositoryFolders.TRENDYOLMANAntrasitErkekBasicRegulaAppFolder(this);
            _tuemueruenlertrendyolgooglechrom = new MyTest4RepositoryFolders.TuemUEruenlerTrendyolGoogleChromAppFolder(this);
            _trendyolmanindigoerkekoversizefitg = new MyTest4RepositoryFolders.TRENDYOLMANIndigoErkekOversizeFitGAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a57be1fa-833d-4bb4-9352-6e07ac5c49d1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAl folder.
        /// </summary>
        [RepositoryFolder("7f474caf-3e81-47ee-9ff1-2946b10ff989")]
        public virtual MyTest4RepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder EnTrendUEruenlerTuerkiyeninOnlineAl
        {
            get { return _entrendueruenlertuerkiyeninonlineal; }
        }

        /// <summary>
        /// The TRENDYOLMANLimitedEditionAntrasitEr folder.
        /// </summary>
        [RepositoryFolder("14d78707-e432-4522-b3d4-b985aae086b9")]
        public virtual MyTest4RepositoryFolders.TRENDYOLMANLimitedEditionAntrasitErAppFolder TRENDYOLMANLimitedEditionAntrasitEr
        {
            get { return _trendyolmanlimitededitionantrasiter; }
        }

        /// <summary>
        /// The RonarexHowToStartChromeAppGoogle folder.
        /// </summary>
        [RepositoryFolder("280d3c41-6d8a-4ad2-b374-82312ac7c632")]
        public virtual MyTest4RepositoryFolders.RonarexHowToStartChromeAppGoogleAppFolder RonarexHowToStartChromeAppGoogle
        {
            get { return _ronarexhowtostartchromeappgoogle; }
        }

        /// <summary>
        /// The TRENDYOLMANAntrasitErkekBasicRegula folder.
        /// </summary>
        [RepositoryFolder("b8bb2128-3491-4fad-b5c8-3b3b08e65301")]
        public virtual MyTest4RepositoryFolders.TRENDYOLMANAntrasitErkekBasicRegulaAppFolder TRENDYOLMANAntrasitErkekBasicRegula
        {
            get { return _trendyolmanantrasiterkekbasicregula; }
        }

        /// <summary>
        /// The TuemUEruenlerTrendyolGoogleChrom folder.
        /// </summary>
        [RepositoryFolder("a80dade8-5037-430e-9952-7feffe51afa7")]
        public virtual MyTest4RepositoryFolders.TuemUEruenlerTrendyolGoogleChromAppFolder TuemUEruenlerTrendyolGoogleChrom
        {
            get { return _tuemueruenlertrendyolgooglechrom; }
        }

        /// <summary>
        /// The TRENDYOLMANIndigoErkekOversizeFitG folder.
        /// </summary>
        [RepositoryFolder("751c122f-1292-4e58-8c71-11e0b6e20ef0")]
        public virtual MyTest4RepositoryFolders.TRENDYOLMANIndigoErkekOversizeFitGAppFolder TRENDYOLMANIndigoErkekOversizeFitG
        {
            get { return _trendyolmanindigoerkekoversizefitg; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest4RepositoryFolders
    {
        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder folder.
        /// </summary>
        [RepositoryFolder("7f474caf-3e81-47ee-9ff1-2946b10ff989")]
        public partial class EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder : RepoGenBaseFolder
        {
            MyTest4RepositoryFolders.PrdctCntnrWrpprFolder _prdctcntnrwrppr;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _loginemailInfo;
            RepoItemInfo _girişyap1Info;
            RepoItemInfo _browsinggwhomepageInfo;
            RepoItemInfo _erkekInfo;
            RepoItemInfo _trendyolmanyenisezonşıklığıInfo;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _flexcontainerInfo;
            SepeteEkle1InfoClass _sepeteekle1Info;
            RepoItemInfo _trendyolmanyenisezonşıklığı1Info;
            RepoItemInfo _productdetailappInfo;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _sepetionaylaInfo;

            /// <summary>
            /// Creates a new EnTrendUEruenlerTuerkiyeninOnlineAl  folder.
            /// </summary>
            public EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnTrendUEruenlerTuerkiyeninOnlineAl", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "7f474caf-3e81-47ee-9ff1-2946b10ff989", "")
            {
                _prdctcntnrwrppr = new MyTest4RepositoryFolders.PrdctCntnrWrpprFolder(this);
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'account-navigation-container']/div/div[1]/?/?/p[@innertext='Giriş Yap']", ".//div[#'account-navigation-container']//p[@innertext='Giriş Yap']", 30000, null, "c13b1868-ccf4-43fe-bd44-e9a8e48390f5");
                _loginemailInfo = new RepoItemInfo(this, "LoginEmail", ".//input[#'login-email']", ".//input[#'login-email']", 30000, null, "5f68699d-ea14-406f-8f6e-f0ba87c49fcc");
                _girişyap1Info = new RepoItemInfo(this, "GirişYap1", ".//div[#'login-register']//form[@action='https://www.trendyol.com/giris?cb=https%3A%2F%2Fwww.trendyol.com%2F%3Fgads%3Dtrue%26tyutm_source%3Dgoogle%26tyutm_medium%3Dcpc%26tyutm_campaign%3Dnew_gl_trendyol_2_x%3Abrand-pure-istanbul%26gclid%3DCj0KCQjwxuCnBhDLARIsAB-cq1rbCLBthwmxGIo42uTqhYLLFjjL47055CW0gazA2-z72Y8ppQ5IHU4aAucYEALw_wcB']/?/?/span[@innertext='Giriş Yap']", ".//div[#'login-register']//form/button/span[@innertext='Giriş Yap']", 30000, null, "259999ee-342d-4cbe-880f-0d70663135b8");
                _browsinggwhomepageInfo = new RepoItemInfo(this, "BrowsingGwHomepage", ".//div[#'browsing-gw-homepage']", ".//div[#'browsing-gw-homepage']", 30000, null, "4bb0e2f8-3662-4d1e-b7e5-aa53d285edd8");
                _erkekInfo = new RepoItemInfo(this, "Erkek", ".//div[#'navigation-wrapper']/nav//a[@innertext='Erkek']", ".//div[#'navigation-wrapper']//a[@innertext='Erkek']", 30000, null, "c9f87678-b2f2-4bdc-8968-1b69ded0dd9d");
                _trendyolmanyenisezonşıklığıInfo = new RepoItemInfo(this, "TRENDYOLMANYeniSezonŞıklığı", ".//div[#'browsing-gw-homepage']/div/div/div/article[4]/a[@href>'https://www.trendyol.com/']/?/?/img[@alt>'TRENDYOL MAN - Yeni Sezon']", ".//div[#'browsing-gw-homepage']//img[@alt>'TRENDYOL MAN - Yeni Sezon']", 30000, null, "560783aa-3096-4499-a1c7-8a66692b70cf");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//main[#'product-detail-app']/div/div[2]/div/div[2]/div[2]/div/div[1]/div[6]/button/div[@innertext='Sepete Ekle']", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", 30000, null, "f4471d72-c21a-4137-84a9-e1ecafd3aa61");
                _flexcontainerInfo = new RepoItemInfo(this, "FlexContainer", ".//main[#'product-detail-app']/div/div[2]", ".//main[#'product-detail-app']/div/div[2]", 30000, null, "fe0282b5-e692-44f9-8456-e8153246121b");
                _sepeteekle1Info = new SepeteEkle1InfoClass(this);
                _trendyolmanyenisezonşıklığı1Info = new RepoItemInfo(this, "TRENDYOLMANYeniSezonŞıklığı1", ".//div[#'browsing-gw-homepage']/div/div/div/article[3]/a[@href>'https://www.trendyol.com/']/?/?/img[@alt>'TRENDYOL MAN - Yeni Sezon']", ".//div[#'browsing-gw-homepage']//img[@alt>'TRENDYOL MAN - Yeni Sezon']", 30000, null, "575b7684-2aca-4e58-8c33-da84bf735928");
                _productdetailappInfo = new RepoItemInfo(this, "ProductDetailApp", ".//main[#'product-detail-app']", ".//main[#'product-detail-app']", 30000, null, "85c316a6-c4a3-4fb3-b46c-029b0bafc83c");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", 30000, null, "a6ecb420-52a0-498c-9620-bf787a9bc738");
                _sepetionaylaInfo = new RepoItemInfo(this, "SepetiOnayla", ".//div[#'pb-container']/aside/div/div[1]/?/?/span[@innertext='Sepeti Onayla']", ".//div[#'pb-container']//span[@innertext='Sepeti Onayla']", 30000, null, "e2f83a63-61c9-4fed-bef1-a22286e57f80");
            }

            /// <summary>
            /// The SepeteEkle1InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("0ed8620f-945e-4997-91cf-13c1743353ca")]
            public class SepeteEkle1InfoClass : RepoItemInfo
            {
                /// <summary>
                /// SepeteEkle1InfoClass class constructor.
                /// </summary>
                public SepeteEkle1InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SepeteEkle1", ".//main[#'product-detail-app']/div/div[2]/div/div[2]/div[2]/div/div[1]/div[5]/button/div[@innertext='Sepete Ekle']", 30000, null, "0ed8620f-945e-4997-91cf-13c1743353ca")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("a433e12e-d930-4ee6-b93a-46d7f12dbfe1")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("a433e12e-d930-4ee6-b93a-46d7f12dbfe1");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("a433e12e-d930-4ee6-b93a-46d7f12dbfe1")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("a433e12e-d930-4ee6-b93a-46d7f12dbfe1", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7f474caf-3e81-47ee-9ff1-2946b10ff989")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7f474caf-3e81-47ee-9ff1-2946b10ff989")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("c13b1868-ccf4-43fe-bd44-e9a8e48390f5")]
            public virtual Ranorex.PTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("c13b1868-ccf4-43fe-bd44-e9a8e48390f5")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The LoginEmail item.
            /// </summary>
            [RepositoryItem("5f68699d-ea14-406f-8f6e-f0ba87c49fcc")]
            public virtual Ranorex.InputTag LoginEmail
            {
                get
                {
                    return _loginemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginEmail item info.
            /// </summary>
            [RepositoryItemInfo("5f68699d-ea14-406f-8f6e-f0ba87c49fcc")]
            public virtual RepoItemInfo LoginEmailInfo
            {
                get
                {
                    return _loginemailInfo;
                }
            }

            /// <summary>
            /// The GirişYap1 item.
            /// </summary>
            [RepositoryItem("259999ee-342d-4cbe-880f-0d70663135b8")]
            public virtual Ranorex.SpanTag GirişYap1
            {
                get
                {
                    return _girişyap1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap1 item info.
            /// </summary>
            [RepositoryItemInfo("259999ee-342d-4cbe-880f-0d70663135b8")]
            public virtual RepoItemInfo GirişYap1Info
            {
                get
                {
                    return _girişyap1Info;
                }
            }

            /// <summary>
            /// The BrowsingGwHomepage item.
            /// </summary>
            [RepositoryItem("4bb0e2f8-3662-4d1e-b7e5-aa53d285edd8")]
            public virtual Ranorex.DivTag BrowsingGwHomepage
            {
                get
                {
                    return _browsinggwhomepageInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The BrowsingGwHomepage item info.
            /// </summary>
            [RepositoryItemInfo("4bb0e2f8-3662-4d1e-b7e5-aa53d285edd8")]
            public virtual RepoItemInfo BrowsingGwHomepageInfo
            {
                get
                {
                    return _browsinggwhomepageInfo;
                }
            }

            /// <summary>
            /// The Erkek item.
            /// </summary>
            [RepositoryItem("c9f87678-b2f2-4bdc-8968-1b69ded0dd9d")]
            public virtual Ranorex.ATag Erkek
            {
                get
                {
                    return _erkekInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Erkek item info.
            /// </summary>
            [RepositoryItemInfo("c9f87678-b2f2-4bdc-8968-1b69ded0dd9d")]
            public virtual RepoItemInfo ErkekInfo
            {
                get
                {
                    return _erkekInfo;
                }
            }

            /// <summary>
            /// The TRENDYOLMANYeniSezonŞıklığı item.
            /// </summary>
            [RepositoryItem("560783aa-3096-4499-a1c7-8a66692b70cf")]
            public virtual Ranorex.ImgTag TRENDYOLMANYeniSezonŞıklığı
            {
                get
                {
                    return _trendyolmanyenisezonşıklığıInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The TRENDYOLMANYeniSezonŞıklığı item info.
            /// </summary>
            [RepositoryItemInfo("560783aa-3096-4499-a1c7-8a66692b70cf")]
            public virtual RepoItemInfo TRENDYOLMANYeniSezonŞıklığıInfo
            {
                get
                {
                    return _trendyolmanyenisezonşıklığıInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("f4471d72-c21a-4137-84a9-e1ecafd3aa61")]
            public virtual Ranorex.DivTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("f4471d72-c21a-4137-84a9-e1ecafd3aa61")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The FlexContainer item.
            /// </summary>
            [RepositoryItem("fe0282b5-e692-44f9-8456-e8153246121b")]
            public virtual Ranorex.DivTag FlexContainer
            {
                get
                {
                    return _flexcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FlexContainer item info.
            /// </summary>
            [RepositoryItemInfo("fe0282b5-e692-44f9-8456-e8153246121b")]
            public virtual RepoItemInfo FlexContainerInfo
            {
                get
                {
                    return _flexcontainerInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle1 item.
            /// </summary>
            [RepositoryItem("0ed8620f-945e-4997-91cf-13c1743353ca")]
            public virtual Ranorex.DivTag SepeteEkle1
            {
                get
                {
                    return _sepeteekle1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle1 item info.
            /// </summary>
            [RepositoryItemInfo("0ed8620f-945e-4997-91cf-13c1743353ca")]
            public virtual SepeteEkle1InfoClass SepeteEkle1Info
            {
                get
                {
                    return _sepeteekle1Info;
                }
            }

            /// <summary>
            /// The TRENDYOLMANYeniSezonŞıklığı1 item.
            /// </summary>
            [RepositoryItem("575b7684-2aca-4e58-8c33-da84bf735928")]
            public virtual Ranorex.ImgTag TRENDYOLMANYeniSezonŞıklığı1
            {
                get
                {
                    return _trendyolmanyenisezonşıklığı1Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The TRENDYOLMANYeniSezonŞıklığı1 item info.
            /// </summary>
            [RepositoryItemInfo("575b7684-2aca-4e58-8c33-da84bf735928")]
            public virtual RepoItemInfo TRENDYOLMANYeniSezonŞıklığı1Info
            {
                get
                {
                    return _trendyolmanyenisezonşıklığı1Info;
                }
            }

            /// <summary>
            /// The ProductDetailApp item.
            /// </summary>
            [RepositoryItem("85c316a6-c4a3-4fb3-b46c-029b0bafc83c")]
            public virtual Ranorex.MainTag ProductDetailApp
            {
                get
                {
                    return _productdetailappInfo.CreateAdapter<Ranorex.MainTag>(true);
                }
            }

            /// <summary>
            /// The ProductDetailApp item info.
            /// </summary>
            [RepositoryItemInfo("85c316a6-c4a3-4fb3-b46c-029b0bafc83c")]
            public virtual RepoItemInfo ProductDetailAppInfo
            {
                get
                {
                    return _productdetailappInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("a6ecb420-52a0-498c-9620-bf787a9bc738")]
            public virtual Ranorex.PTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("a6ecb420-52a0-498c-9620-bf787a9bc738")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The SepetiOnayla item.
            /// </summary>
            [RepositoryItem("e2f83a63-61c9-4fed-bef1-a22286e57f80")]
            public virtual Ranorex.SpanTag SepetiOnayla
            {
                get
                {
                    return _sepetionaylaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SepetiOnayla item info.
            /// </summary>
            [RepositoryItemInfo("e2f83a63-61c9-4fed-bef1-a22286e57f80")]
            public virtual RepoItemInfo SepetiOnaylaInfo
            {
                get
                {
                    return _sepetionaylaInfo;
                }
            }

            /// <summary>
            /// The PrdctCntnrWrppr folder.
            /// </summary>
            [RepositoryFolder("881bc940-6b54-4484-8639-3f24f7ea5676")]
            public virtual MyTest4RepositoryFolders.PrdctCntnrWrpprFolder PrdctCntnrWrppr
            {
                get { return _prdctcntnrwrppr; }
            }
        }

        /// <summary>
        /// The PrdctCntnrWrpprFolder folder.
        /// </summary>
        [RepositoryFolder("881bc940-6b54-4484-8639-3f24f7ea5676")]
        public partial class PrdctCntnrWrpprFolder : RepoGenBaseFolder
        {
            RepoItemInfo _imageoverlaybodyInfo;
            RepoItemInfo _fvrtbtn8Info;
            RepoItemInfo _fvrtbtn9Info;
            RepoItemInfo _fvrtbtn10Info;
            RepoItemInfo _fvrtbtnInfo;
            RepoItemInfo _fvrtbtn1Info;
            RepoItemInfo _fvrtbtn2Info;
            RepoItemInfo _fvrtbtn3Info;
            RepoItemInfo _fvrtbtn4Info;
            RepoItemInfo _fvrtbtn5Info;
            RepoItemInfo _imageoverlaybody2Info;
            RepoItemInfo _fvrtbtn6Info;
            RepoItemInfo _imageoverlaybody1Info;
            RepoItemInfo _fvrtbtn7Info;
            RepoItemInfo _imageoverlaybody3Info;
            RepoItemInfo _imageoverlaybody4Info;
            RepoItemInfo _imageoverlayInfo;
            RepoItemInfo _imageoverlaybody5Info;
            RepoItemInfo _imageoverlaybody6Info;
            RepoItemInfo _imageoverlaybody7Info;
            RepoItemInfo _imageoverlaybody8Info;
            RepoItemInfo _fvrtbtn11Info;
            RepoItemInfo _imageoverlaybody9Info;

            /// <summary>
            /// Creates a new PrdctCntnrWrppr  folder.
            /// </summary>
            public PrdctCntnrWrpprFolder(RepoGenBaseFolder parentFolder) :
                    base("PrdctCntnrWrppr", ".//div[#'search-app']/div/div[1]/div[2]/div[4]/div[1]/div", parentFolder, 30000, null, false, "881bc940-6b54-4484-8639-3f24f7ea5676", "")
            {
                _imageoverlaybodyInfo = new RepoItemInfo(this, "ImageOverlayBody", "div[10]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[10]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "98f63552-c86d-4cb4-bf06-32344fdf53d2");
                _fvrtbtn8Info = new RepoItemInfo(this, "FvrtBtn8", "div[10]/?/?/i", "div[10]/div[2]/i", 30000, null, "2a8b8b1f-042b-42bf-989a-da63377ff872");
                _fvrtbtn9Info = new RepoItemInfo(this, "FvrtBtn9", "div[11]/?/?/i", "div[11]/div[2]/i", 30000, null, "90cee9ba-a446-4070-9e32-bd165feb8c73");
                _fvrtbtn10Info = new RepoItemInfo(this, "FvrtBtn10", "div[12]/?/?/i", "div[12]/div[2]/i", 30000, null, "c7672950-62d5-4dea-b4f4-ebfe09025688");
                _fvrtbtnInfo = new RepoItemInfo(this, "FvrtBtn", "div[2]/?/?/i", "div[2]/div[2]/i", 30000, null, "6dfc5cb7-c73b-4dfc-b103-f99a90ed45a2");
                _fvrtbtn1Info = new RepoItemInfo(this, "FvrtBtn1", "div[3]/?/?/i", "div[3]/div[2]/i", 30000, null, "b502aaa1-dcba-4647-8307-e7a3ab66eb6f");
                _fvrtbtn2Info = new RepoItemInfo(this, "FvrtBtn2", "div[4]/?/?/i", "div[4]/div[2]/i", 30000, null, "88065e52-9025-48fa-8059-55b5611f9bbd");
                _fvrtbtn3Info = new RepoItemInfo(this, "FvrtBtn3", "div[5]/?/?/i", "div[5]/div[2]/i", 30000, null, "7174033a-eb63-4429-942a-f5ef0a477dab");
                _fvrtbtn4Info = new RepoItemInfo(this, "FvrtBtn4", "div[6]/?/?/i", "div[6]/div[2]/i", 30000, null, "679f5d74-d5f3-4849-881b-2a23646ccfca");
                _fvrtbtn5Info = new RepoItemInfo(this, "FvrtBtn5", "div[7]/?/?/i", "div[7]/div[2]/i", 30000, null, "f87360d4-c779-4689-ad7f-283bf751a32d");
                _imageoverlaybody2Info = new RepoItemInfo(this, "ImageOverlayBody2", "div[8]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[8]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "4958c98e-37a8-40a5-bad1-fe9732ecaf4a");
                _fvrtbtn6Info = new RepoItemInfo(this, "FvrtBtn6", "div[8]/?/?/i", "div[8]/div[2]/i", 30000, null, "9f5f2e23-4cd1-4f09-b706-2fc0226f6fa2");
                _imageoverlaybody1Info = new RepoItemInfo(this, "ImageOverlayBody1", "div[9]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[9]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "3b4b96ad-3544-45bb-8e8f-74936eba3d62");
                _fvrtbtn7Info = new RepoItemInfo(this, "FvrtBtn7", "div[9]/?/?/i", "div[9]/div[2]/i", 30000, null, "c0049107-209a-49ff-ba80-2b35400e2be5");
                _imageoverlaybody3Info = new RepoItemInfo(this, "ImageOverlayBody3", "div[7]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[7]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "2109f31a-535d-4b24-96a3-845c3f2de1df");
                _imageoverlaybody4Info = new RepoItemInfo(this, "ImageOverlayBody4", "div[6]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[6]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "9bff2f89-56ef-47e2-91f4-f0ca49d0443e");
                _imageoverlayInfo = new RepoItemInfo(this, "ImageOverlay", "div[5]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]", "div[5]/div/a[@href>'https://www.trendyol.com/']/div[1]/div[2]", 30000, null, "0c4ddb44-aaa2-4ee4-b5ce-a9ad908b4e0d");
                _imageoverlaybody5Info = new RepoItemInfo(this, "ImageOverlayBody5", "div[4]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[4]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "9836a59c-9630-4eaf-aa58-7381fe89a210");
                _imageoverlaybody6Info = new RepoItemInfo(this, "ImageOverlayBody6", "div[3]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[3]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "3ba27a77-0c73-4f74-a5c3-1dd04a941fe4");
                _imageoverlaybody7Info = new RepoItemInfo(this, "ImageOverlayBody7", "div[2]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[2]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "63e92865-32ca-4b4f-af7f-cbd3e5bf3990");
                _imageoverlaybody8Info = new RepoItemInfo(this, "ImageOverlayBody8", "div[1]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[1]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "7ca14e70-1a3c-4619-bcb4-8d0c9e53f8fa");
                _fvrtbtn11Info = new RepoItemInfo(this, "FvrtBtn11", "div[1]/?/?/i", "div[1]/div[2]/i", 30000, null, "fd38c1de-7c94-433b-b307-ff6d3baf9fda");
                _imageoverlaybody9Info = new RepoItemInfo(this, "ImageOverlayBody9", "div[5]/?/?/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", "div[5]/div[1]/a[@href>'https://www.trendyol.com/']/div[1]/div[2]/div[2]", 30000, null, "7224f786-4766-4650-86a7-5a2f51b3dc28");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("881bc940-6b54-4484-8639-3f24f7ea5676")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("881bc940-6b54-4484-8639-3f24f7ea5676")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ImageOverlayBody item.
            /// </summary>
            [RepositoryItem("98f63552-c86d-4cb4-bf06-32344fdf53d2")]
            public virtual Ranorex.DivTag ImageOverlayBody
            {
                get
                {
                    return _imageoverlaybodyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody item info.
            /// </summary>
            [RepositoryItemInfo("98f63552-c86d-4cb4-bf06-32344fdf53d2")]
            public virtual RepoItemInfo ImageOverlayBodyInfo
            {
                get
                {
                    return _imageoverlaybodyInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn8 item.
            /// </summary>
            [RepositoryItem("2a8b8b1f-042b-42bf-989a-da63377ff872")]
            public virtual Ranorex.ITag FvrtBtn8
            {
                get
                {
                    return _fvrtbtn8Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn8 item info.
            /// </summary>
            [RepositoryItemInfo("2a8b8b1f-042b-42bf-989a-da63377ff872")]
            public virtual RepoItemInfo FvrtBtn8Info
            {
                get
                {
                    return _fvrtbtn8Info;
                }
            }

            /// <summary>
            /// The FvrtBtn9 item.
            /// </summary>
            [RepositoryItem("90cee9ba-a446-4070-9e32-bd165feb8c73")]
            public virtual Ranorex.ITag FvrtBtn9
            {
                get
                {
                    return _fvrtbtn9Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn9 item info.
            /// </summary>
            [RepositoryItemInfo("90cee9ba-a446-4070-9e32-bd165feb8c73")]
            public virtual RepoItemInfo FvrtBtn9Info
            {
                get
                {
                    return _fvrtbtn9Info;
                }
            }

            /// <summary>
            /// The FvrtBtn10 item.
            /// </summary>
            [RepositoryItem("c7672950-62d5-4dea-b4f4-ebfe09025688")]
            public virtual Ranorex.ITag FvrtBtn10
            {
                get
                {
                    return _fvrtbtn10Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn10 item info.
            /// </summary>
            [RepositoryItemInfo("c7672950-62d5-4dea-b4f4-ebfe09025688")]
            public virtual RepoItemInfo FvrtBtn10Info
            {
                get
                {
                    return _fvrtbtn10Info;
                }
            }

            /// <summary>
            /// The FvrtBtn item.
            /// </summary>
            [RepositoryItem("6dfc5cb7-c73b-4dfc-b103-f99a90ed45a2")]
            public virtual Ranorex.ITag FvrtBtn
            {
                get
                {
                    return _fvrtbtnInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn item info.
            /// </summary>
            [RepositoryItemInfo("6dfc5cb7-c73b-4dfc-b103-f99a90ed45a2")]
            public virtual RepoItemInfo FvrtBtnInfo
            {
                get
                {
                    return _fvrtbtnInfo;
                }
            }

            /// <summary>
            /// The FvrtBtn1 item.
            /// </summary>
            [RepositoryItem("b502aaa1-dcba-4647-8307-e7a3ab66eb6f")]
            public virtual Ranorex.ITag FvrtBtn1
            {
                get
                {
                    return _fvrtbtn1Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn1 item info.
            /// </summary>
            [RepositoryItemInfo("b502aaa1-dcba-4647-8307-e7a3ab66eb6f")]
            public virtual RepoItemInfo FvrtBtn1Info
            {
                get
                {
                    return _fvrtbtn1Info;
                }
            }

            /// <summary>
            /// The FvrtBtn2 item.
            /// </summary>
            [RepositoryItem("88065e52-9025-48fa-8059-55b5611f9bbd")]
            public virtual Ranorex.ITag FvrtBtn2
            {
                get
                {
                    return _fvrtbtn2Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn2 item info.
            /// </summary>
            [RepositoryItemInfo("88065e52-9025-48fa-8059-55b5611f9bbd")]
            public virtual RepoItemInfo FvrtBtn2Info
            {
                get
                {
                    return _fvrtbtn2Info;
                }
            }

            /// <summary>
            /// The FvrtBtn3 item.
            /// </summary>
            [RepositoryItem("7174033a-eb63-4429-942a-f5ef0a477dab")]
            public virtual Ranorex.ITag FvrtBtn3
            {
                get
                {
                    return _fvrtbtn3Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn3 item info.
            /// </summary>
            [RepositoryItemInfo("7174033a-eb63-4429-942a-f5ef0a477dab")]
            public virtual RepoItemInfo FvrtBtn3Info
            {
                get
                {
                    return _fvrtbtn3Info;
                }
            }

            /// <summary>
            /// The FvrtBtn4 item.
            /// </summary>
            [RepositoryItem("679f5d74-d5f3-4849-881b-2a23646ccfca")]
            public virtual Ranorex.ITag FvrtBtn4
            {
                get
                {
                    return _fvrtbtn4Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn4 item info.
            /// </summary>
            [RepositoryItemInfo("679f5d74-d5f3-4849-881b-2a23646ccfca")]
            public virtual RepoItemInfo FvrtBtn4Info
            {
                get
                {
                    return _fvrtbtn4Info;
                }
            }

            /// <summary>
            /// The FvrtBtn5 item.
            /// </summary>
            [RepositoryItem("f87360d4-c779-4689-ad7f-283bf751a32d")]
            public virtual Ranorex.ITag FvrtBtn5
            {
                get
                {
                    return _fvrtbtn5Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn5 item info.
            /// </summary>
            [RepositoryItemInfo("f87360d4-c779-4689-ad7f-283bf751a32d")]
            public virtual RepoItemInfo FvrtBtn5Info
            {
                get
                {
                    return _fvrtbtn5Info;
                }
            }

            /// <summary>
            /// The ImageOverlayBody2 item.
            /// </summary>
            [RepositoryItem("4958c98e-37a8-40a5-bad1-fe9732ecaf4a")]
            public virtual Ranorex.DivTag ImageOverlayBody2
            {
                get
                {
                    return _imageoverlaybody2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody2 item info.
            /// </summary>
            [RepositoryItemInfo("4958c98e-37a8-40a5-bad1-fe9732ecaf4a")]
            public virtual RepoItemInfo ImageOverlayBody2Info
            {
                get
                {
                    return _imageoverlaybody2Info;
                }
            }

            /// <summary>
            /// The FvrtBtn6 item.
            /// </summary>
            [RepositoryItem("9f5f2e23-4cd1-4f09-b706-2fc0226f6fa2")]
            public virtual Ranorex.ITag FvrtBtn6
            {
                get
                {
                    return _fvrtbtn6Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn6 item info.
            /// </summary>
            [RepositoryItemInfo("9f5f2e23-4cd1-4f09-b706-2fc0226f6fa2")]
            public virtual RepoItemInfo FvrtBtn6Info
            {
                get
                {
                    return _fvrtbtn6Info;
                }
            }

            /// <summary>
            /// The ImageOverlayBody1 item.
            /// </summary>
            [RepositoryItem("3b4b96ad-3544-45bb-8e8f-74936eba3d62")]
            public virtual Ranorex.DivTag ImageOverlayBody1
            {
                get
                {
                    return _imageoverlaybody1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody1 item info.
            /// </summary>
            [RepositoryItemInfo("3b4b96ad-3544-45bb-8e8f-74936eba3d62")]
            public virtual RepoItemInfo ImageOverlayBody1Info
            {
                get
                {
                    return _imageoverlaybody1Info;
                }
            }

            /// <summary>
            /// The FvrtBtn7 item.
            /// </summary>
            [RepositoryItem("c0049107-209a-49ff-ba80-2b35400e2be5")]
            public virtual Ranorex.ITag FvrtBtn7
            {
                get
                {
                    return _fvrtbtn7Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn7 item info.
            /// </summary>
            [RepositoryItemInfo("c0049107-209a-49ff-ba80-2b35400e2be5")]
            public virtual RepoItemInfo FvrtBtn7Info
            {
                get
                {
                    return _fvrtbtn7Info;
                }
            }

            /// <summary>
            /// The ImageOverlayBody3 item.
            /// </summary>
            [RepositoryItem("2109f31a-535d-4b24-96a3-845c3f2de1df")]
            public virtual Ranorex.DivTag ImageOverlayBody3
            {
                get
                {
                    return _imageoverlaybody3Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody3 item info.
            /// </summary>
            [RepositoryItemInfo("2109f31a-535d-4b24-96a3-845c3f2de1df")]
            public virtual RepoItemInfo ImageOverlayBody3Info
            {
                get
                {
                    return _imageoverlaybody3Info;
                }
            }

            /// <summary>
            /// The ImageOverlayBody4 item.
            /// </summary>
            [RepositoryItem("9bff2f89-56ef-47e2-91f4-f0ca49d0443e")]
            public virtual Ranorex.DivTag ImageOverlayBody4
            {
                get
                {
                    return _imageoverlaybody4Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody4 item info.
            /// </summary>
            [RepositoryItemInfo("9bff2f89-56ef-47e2-91f4-f0ca49d0443e")]
            public virtual RepoItemInfo ImageOverlayBody4Info
            {
                get
                {
                    return _imageoverlaybody4Info;
                }
            }

            /// <summary>
            /// The ImageOverlay item.
            /// </summary>
            [RepositoryItem("0c4ddb44-aaa2-4ee4-b5ce-a9ad908b4e0d")]
            public virtual Ranorex.DivTag ImageOverlay
            {
                get
                {
                    return _imageoverlayInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlay item info.
            /// </summary>
            [RepositoryItemInfo("0c4ddb44-aaa2-4ee4-b5ce-a9ad908b4e0d")]
            public virtual RepoItemInfo ImageOverlayInfo
            {
                get
                {
                    return _imageoverlayInfo;
                }
            }

            /// <summary>
            /// The ImageOverlayBody5 item.
            /// </summary>
            [RepositoryItem("9836a59c-9630-4eaf-aa58-7381fe89a210")]
            public virtual Ranorex.DivTag ImageOverlayBody5
            {
                get
                {
                    return _imageoverlaybody5Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody5 item info.
            /// </summary>
            [RepositoryItemInfo("9836a59c-9630-4eaf-aa58-7381fe89a210")]
            public virtual RepoItemInfo ImageOverlayBody5Info
            {
                get
                {
                    return _imageoverlaybody5Info;
                }
            }

            /// <summary>
            /// The ImageOverlayBody6 item.
            /// </summary>
            [RepositoryItem("3ba27a77-0c73-4f74-a5c3-1dd04a941fe4")]
            public virtual Ranorex.DivTag ImageOverlayBody6
            {
                get
                {
                    return _imageoverlaybody6Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody6 item info.
            /// </summary>
            [RepositoryItemInfo("3ba27a77-0c73-4f74-a5c3-1dd04a941fe4")]
            public virtual RepoItemInfo ImageOverlayBody6Info
            {
                get
                {
                    return _imageoverlaybody6Info;
                }
            }

            /// <summary>
            /// The ImageOverlayBody7 item.
            /// </summary>
            [RepositoryItem("63e92865-32ca-4b4f-af7f-cbd3e5bf3990")]
            public virtual Ranorex.DivTag ImageOverlayBody7
            {
                get
                {
                    return _imageoverlaybody7Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody7 item info.
            /// </summary>
            [RepositoryItemInfo("63e92865-32ca-4b4f-af7f-cbd3e5bf3990")]
            public virtual RepoItemInfo ImageOverlayBody7Info
            {
                get
                {
                    return _imageoverlaybody7Info;
                }
            }

            /// <summary>
            /// The ImageOverlayBody8 item.
            /// </summary>
            [RepositoryItem("7ca14e70-1a3c-4619-bcb4-8d0c9e53f8fa")]
            public virtual Ranorex.DivTag ImageOverlayBody8
            {
                get
                {
                    return _imageoverlaybody8Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody8 item info.
            /// </summary>
            [RepositoryItemInfo("7ca14e70-1a3c-4619-bcb4-8d0c9e53f8fa")]
            public virtual RepoItemInfo ImageOverlayBody8Info
            {
                get
                {
                    return _imageoverlaybody8Info;
                }
            }

            /// <summary>
            /// The FvrtBtn11 item.
            /// </summary>
            [RepositoryItem("fd38c1de-7c94-433b-b307-ff6d3baf9fda")]
            public virtual Ranorex.ITag FvrtBtn11
            {
                get
                {
                    return _fvrtbtn11Info.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The FvrtBtn11 item info.
            /// </summary>
            [RepositoryItemInfo("fd38c1de-7c94-433b-b307-ff6d3baf9fda")]
            public virtual RepoItemInfo FvrtBtn11Info
            {
                get
                {
                    return _fvrtbtn11Info;
                }
            }

            /// <summary>
            /// The ImageOverlayBody9 item.
            /// </summary>
            [RepositoryItem("7224f786-4766-4650-86a7-5a2f51b3dc28")]
            public virtual Ranorex.DivTag ImageOverlayBody9
            {
                get
                {
                    return _imageoverlaybody9Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ImageOverlayBody9 item info.
            /// </summary>
            [RepositoryItemInfo("7224f786-4766-4650-86a7-5a2f51b3dc28")]
            public virtual RepoItemInfo ImageOverlayBody9Info
            {
                get
                {
                    return _imageoverlaybody9Info;
                }
            }
        }

        /// <summary>
        /// The TRENDYOLMANLimitedEditionAntrasitErAppFolder folder.
        /// </summary>
        [RepositoryFolder("14d78707-e432-4522-b3d4-b985aae086b9")]
        public partial class TRENDYOLMANLimitedEditionAntrasitErAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;
            RepoItemInfo _pane1Info;
            RepoItemInfo _pane2Info;
            RepoItemInfo _pane3Info;
            RepoItemInfo _pane4Info;
            RepoItemInfo _geriInfo;
            RepoItemInfo _pane5Info;
            RepoItemInfo _pane6Info;

            /// <summary>
            /// Creates a new TRENDYOLMANLimitedEditionAntrasitEr  folder.
            /// </summary>
            public TRENDYOLMANLimitedEditionAntrasitErAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TRENDYOLMANLimitedEditionAntrasitEr", "/form[@title>'TRENDYOL MAN Limited Edition']", parentFolder, 30000, null, true, "14d78707-e432-4522-b3d4-b985aae086b9", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'TRENDYOL MAN Limited Edition']/container/container[@accessiblerole='Pane']/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "614310f9-404e-43c1-b06d-9f962a0d36eb");
                _pane1Info = new RepoItemInfo(this, "Pane1", "container[@accessiblename>'TRENDYOL MAN Siyah Erkek Oversize']/container/container[@accessiblerole='Pane']/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "454407ff-aaf1-459c-b0a9-7bf16860b973");
                _pane2Info = new RepoItemInfo(this, "Pane2", "container[@accessiblename>'TRENDYOL MAN Antrasit Erkek']/container/container[@accessiblerole='Pane']/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "0dc8104a-4564-4e49-ba66-4bf48ed67677");
                _pane3Info = new RepoItemInfo(this, "Pane3", "container[@accessiblename>'TRENDYOL MAN Siyah Erkek Basic']/container/container[@accessiblerole='Pane']/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "289d217b-2b54-4065-aab8-751bd81c95a8");
                _pane4Info = new RepoItemInfo(this, "Pane4", "container[@accessiblename>'TRENDYOL MAN Gri Erkek Regular/Normal']/container/container[@accessiblerole='Pane']/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "5355e545-c8f5-4fb5-9163-a5dc4f06d96d");
                _geriInfo = new RepoItemInfo(this, "Geri", "container[@accessiblename>'TRENDYOL MAN Limited Edition']/container/container[@accessiblerole='Pane']/container[2]/container[1]/toolbar[1]/?/?/button[@accessiblename='Geri']", ".//button[@accessiblename='Geri']", 30000, null, "604927bd-f246-46bd-8556-2b1dc6b6e15e");
                _pane5Info = new RepoItemInfo(this, "Pane5", "container[@accessiblename>'Trendyol Man Tişört Erkek']/container/container[@accessiblerole='Pane']/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "cb32890c-47d9-43e2-a33c-dd0787325a39");
                _pane6Info = new RepoItemInfo(this, "Pane6", "container[@accessiblename>'TRENDYOL MAN Indigo Erkek']/container/container[@accessiblerole='Pane']/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "611d0d57-3577-4803-8179-bc69776afcd5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("14d78707-e432-4522-b3d4-b985aae086b9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("14d78707-e432-4522-b3d4-b985aae086b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("614310f9-404e-43c1-b06d-9f962a0d36eb")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("614310f9-404e-43c1-b06d-9f962a0d36eb")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Pane1 item.
            /// </summary>
            [RepositoryItem("454407ff-aaf1-459c-b0a9-7bf16860b973")]
            public virtual Ranorex.Container Pane1
            {
                get
                {
                    return _pane1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane1 item info.
            /// </summary>
            [RepositoryItemInfo("454407ff-aaf1-459c-b0a9-7bf16860b973")]
            public virtual RepoItemInfo Pane1Info
            {
                get
                {
                    return _pane1Info;
                }
            }

            /// <summary>
            /// The Pane2 item.
            /// </summary>
            [RepositoryItem("0dc8104a-4564-4e49-ba66-4bf48ed67677")]
            public virtual Ranorex.Container Pane2
            {
                get
                {
                    return _pane2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane2 item info.
            /// </summary>
            [RepositoryItemInfo("0dc8104a-4564-4e49-ba66-4bf48ed67677")]
            public virtual RepoItemInfo Pane2Info
            {
                get
                {
                    return _pane2Info;
                }
            }

            /// <summary>
            /// The Pane3 item.
            /// </summary>
            [RepositoryItem("289d217b-2b54-4065-aab8-751bd81c95a8")]
            public virtual Ranorex.Container Pane3
            {
                get
                {
                    return _pane3Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane3 item info.
            /// </summary>
            [RepositoryItemInfo("289d217b-2b54-4065-aab8-751bd81c95a8")]
            public virtual RepoItemInfo Pane3Info
            {
                get
                {
                    return _pane3Info;
                }
            }

            /// <summary>
            /// The Pane4 item.
            /// </summary>
            [RepositoryItem("5355e545-c8f5-4fb5-9163-a5dc4f06d96d")]
            public virtual Ranorex.Container Pane4
            {
                get
                {
                    return _pane4Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane4 item info.
            /// </summary>
            [RepositoryItemInfo("5355e545-c8f5-4fb5-9163-a5dc4f06d96d")]
            public virtual RepoItemInfo Pane4Info
            {
                get
                {
                    return _pane4Info;
                }
            }

            /// <summary>
            /// The Geri item.
            /// </summary>
            [RepositoryItem("604927bd-f246-46bd-8556-2b1dc6b6e15e")]
            public virtual Ranorex.Button Geri
            {
                get
                {
                    return _geriInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Geri item info.
            /// </summary>
            [RepositoryItemInfo("604927bd-f246-46bd-8556-2b1dc6b6e15e")]
            public virtual RepoItemInfo GeriInfo
            {
                get
                {
                    return _geriInfo;
                }
            }

            /// <summary>
            /// The Pane5 item.
            /// </summary>
            [RepositoryItem("cb32890c-47d9-43e2-a33c-dd0787325a39")]
            public virtual Ranorex.Container Pane5
            {
                get
                {
                    return _pane5Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane5 item info.
            /// </summary>
            [RepositoryItemInfo("cb32890c-47d9-43e2-a33c-dd0787325a39")]
            public virtual RepoItemInfo Pane5Info
            {
                get
                {
                    return _pane5Info;
                }
            }

            /// <summary>
            /// The Pane6 item.
            /// </summary>
            [RepositoryItem("611d0d57-3577-4803-8179-bc69776afcd5")]
            public virtual Ranorex.Container Pane6
            {
                get
                {
                    return _pane6Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane6 item info.
            /// </summary>
            [RepositoryItemInfo("611d0d57-3577-4803-8179-bc69776afcd5")]
            public virtual RepoItemInfo Pane6Info
            {
                get
                {
                    return _pane6Info;
                }
            }
        }

        /// <summary>
        /// The RonarexHowToStartChromeAppGoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("280d3c41-6d8a-4ad2-b374-82312ac7c632")]
        public partial class RonarexHowToStartChromeAppGoogleAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new RonarexHowToStartChromeAppGoogle  folder.
            /// </summary>
            public RonarexHowToStartChromeAppGoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RonarexHowToStartChromeAppGoogle", "/dom[@domain='www.google.com']", parentFolder, 30000, null, false, "280d3c41-6d8a-4ad2-b374-82312ac7c632", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("280d3c41-6d8a-4ad2-b374-82312ac7c632")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("280d3c41-6d8a-4ad2-b374-82312ac7c632")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The TRENDYOLMANAntrasitErkekBasicRegulaAppFolder folder.
        /// </summary>
        [RepositoryFolder("b8bb2128-3491-4fad-b5c8-3b3b08e65301")]
        public partial class TRENDYOLMANAntrasitErkekBasicRegulaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new TRENDYOLMANAntrasitErkekBasicRegula  folder.
            /// </summary>
            public TRENDYOLMANAntrasitErkekBasicRegulaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TRENDYOLMANAntrasitErkekBasicRegula", "/form[@title>'TRENDYOL MAN Antrasit Erkek']", parentFolder, 30000, null, true, "b8bb2128-3491-4fad-b5c8-3b3b08e65301", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'TRENDYOL MAN Antrasit Erkek']/container/container[@accessiblerole='Pane']/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "64031e03-7020-4e86-bbfb-1b0a97a20524");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b8bb2128-3491-4fad-b5c8-3b3b08e65301")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b8bb2128-3491-4fad-b5c8-3b3b08e65301")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("64031e03-7020-4e86-bbfb-1b0a97a20524")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("64031e03-7020-4e86-bbfb-1b0a97a20524")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

        /// <summary>
        /// The TuemUEruenlerTrendyolGoogleChromAppFolder folder.
        /// </summary>
        [RepositoryFolder("a80dade8-5037-430e-9952-7feffe51afa7")]
        public partial class TuemUEruenlerTrendyolGoogleChromAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new TuemUEruenlerTrendyolGoogleChrom  folder.
            /// </summary>
            public TuemUEruenlerTrendyolGoogleChromAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TuemUEruenlerTrendyolGoogleChrom", "/form[@title>'Tüm Ürünler - Trendyol - Google']", parentFolder, 30000, null, true, "a80dade8-5037-430e-9952-7feffe51afa7", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'Tüm Ürünler - Trendyol - Google']/container/container[@accessiblerole='Pane']/container[2]/container[1]", "?/?/container/container[@accessiblerole='Pane']/container[2]/container[1]", 30000, null, "76b3410f-45c6-4812-b64c-afc0e7b0bbf0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a80dade8-5037-430e-9952-7feffe51afa7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a80dade8-5037-430e-9952-7feffe51afa7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("76b3410f-45c6-4812-b64c-afc0e7b0bbf0")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("76b3410f-45c6-4812-b64c-afc0e7b0bbf0")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

        /// <summary>
        /// The TRENDYOLMANIndigoErkekOversizeFitGAppFolder folder.
        /// </summary>
        [RepositoryFolder("751c122f-1292-4e58-8c71-11e0b6e20ef0")]
        public partial class TRENDYOLMANIndigoErkekOversizeFitGAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new TRENDYOLMANIndigoErkekOversizeFitG  folder.
            /// </summary>
            public TRENDYOLMANIndigoErkekOversizeFitGAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TRENDYOLMANIndigoErkekOversizeFitG", "/form[@title>'TRENDYOL MAN Indigo Erkek']", parentFolder, 30000, null, true, "751c122f-1292-4e58-8c71-11e0b6e20ef0", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'TRENDYOL MAN Indigo Erkek']/container/container[@accessiblerole='Pane']/container[2]/container[1]/tabpagelist[@accessiblerole='PageTabList']/container[1]/container[2]", ".//tabpagelist/container[1]/container[2]", 30000, null, "40768ea3-7645-4848-a0d6-8a5713953185");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("751c122f-1292-4e58-8c71-11e0b6e20ef0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("751c122f-1292-4e58-8c71-11e0b6e20ef0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("40768ea3-7645-4848-a0d6-8a5713953185")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("40768ea3-7645-4848-a0d6-8a5713953185")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
